config/routes.rb
Rails.application.routes.draw do

  scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
    root "products#index"
    resources :product_types
    resources :orders
    #resources :payment_notifications
    resources :carts
    resources :cart_items
    resources :products
    resources :searches
    resources :categories
    resources :letters
    get 'current_cart', action: :show, controller: 'carts'
    #current_cart 'cart', :controller => 'carts', :action => 'show'
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.ht
  end
  get '*path', to: redirect("/#{I18n.default_locale}/%{path}"), constraints: lambda { |req| !req.path.starts_with? "/#{I18n.default_locale}/" }
  get '', to: redirect("/#{I18n.default_locale}")
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
	has_many :cart_items
	has_many :products, :through => :cart_items
  has_one :order
	
	def total_price
		cart_items.to_a.sum(&:full_price)
	end

def paypal_url(return_url, notify_url)
  values = {
    :business => 'sb-n9vvk38491@business.example.com',
    :cmd => '_cart',
    :upload => 1,
    :return => return_url,
    :invoice => id,
    :notify_url => notify_url
  }
  cart_items.each_with_index do |item, index|
    values.merge!({
      "amount_#{index+1}" => item.unit_price,
      "item_name_#{index+1}" => item.product.name,
      "item_number_#{index+1}" => item.id,
      "quantity_#{index+1}" => item.quantity
    })
  end
  "https://www.sandbox.paypal.com/cgi-bin/webscr?" + values.to_query
end

end

app/models/cart_item.rb
class CartItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :cart
  before_create :default_quantity_to_one
  
  def full_price
    self.unit_price * quantity
  end
  
  private
  
  def default_quantity_to_one
    self.quantity ||= 1
  end

end

app/models/category.rb
class Category < ApplicationRecord
	has_many :products
	has_ancestry
end

app/models/letter.rb
class Letter
    include ActiveModel::Model
    attr_reader :char

  def self.all
    ('A'..'Z').map { |c| new(c) }
  end
  
  def self.find(param)
    self.all.detect { |l| l.to_param == param } || raise(ActiveRecord::RecordNotFound)
  end
  
  def initialize(char)
    @char = char
  end
  
  def to_param
    @char.downcase
  end
  
  def products
    #Product.find(:all, :conditions => ["name LIKE ?", @char + '%'], :order => "name")
    Product.all.where(["name LIKE ?", @char + '%']).order(:name)

  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :cart
  has_many :transactions, :class_name => "OrderTransaction"

   attr_accessor :card_number, :card_verification

  #validate_on_create :validate_card  - deprecated
  validate :validate_card, :on => :create
  
  def purchase
    response = GATEWAY.purchase(price_in_cents, credit_card, purchase_options)
    transactions.create!(:action => "purchase", :amount => price_in_cents, :response => response)
    cart.update_attribute(:purchased_at, Time.now) if response.success?
    response.success?
  end
  
  def price_in_cents
    (cart.total_price*100).round
  end

  private
  
  def purchase_options
    {
      :ip => ip_address,
      :billing_address => {
        :name     => "Dieudonne Shopper",
        :address1 => "123 Main St.",
        :city     => "New York",
        :state    => "NY",
        :country  => "US",
        :zip      => "10001"
      }
    }
  end
  
  def validate_card
    unless credit_card.valid?
      credit_card.errors.full_messages.each do |message|
        #errors.add_to_base message, depreciated in rails 5
        errors[:base] << message 
      end
    end
  end
  
  def credit_card
    @credit_card ||= ActiveMerchant::Billing::CreditCard.new(
      :type               => card_type,
      :number             => card_number,
      :verification_value => card_verification,
      :month              => card_expires_on.month,
      :year               => card_expires_on.year,
      :first_name         => first_name,
      :last_name          => last_name
    )
  end
end

app/models/order_transaction.rb
class OrderTransaction < ActiveRecord::Base
  belongs_to :order
  serialize :params
  
  def response=(response)
    self.success       = response.success?
    self.authorization = response.authorization
    self.message       = response.message
    self.params        = response.params
  rescue ActiveMerchant::ActiveMerchantError => e
    self.success       = false
    self.authorization = nil
    self.message       = e.message
    self.params        = {}
  end
end

app/models/payment_notification.rb
class PaymentNotification < ActiveRecord::Base
	belongs_to :cart

	def create
	  PaymentNotification.create!(:params => params, :cart_id => params[:invoice], :status => params[:payment_status], :transaction_id => params[:txn_id])
	  render :nothing => true
	end
end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :category
	has_many :cart_items
	belongs_to :product_type
	serialize :properties, Hash
	validate :validate_properties

	def self.search(search)
		if search
			self.all.order(:name).where(['name LIKE ?', "%#{search}%"])
		else
			self.all
		end
	end

	def category_name
		category.try(:name)
	end

	def category_name=(name)
		self.category = Category.find_or_create_by(name: name) if name.present?
	end



  validate :validate_properties
  
  def validate_properties
    product_type.fields.each do |field|
      if field.required? && properties[field.name].blank?
        errors.add field.name, "must not be blank"
      end
    end
  end
  
end

app/models/product_field.rb
class ProductField < ApplicationRecord
  belongs_to :product_type
end

app/models/product_type.rb
class ProductType < ApplicationRecord
	  has_many :fields, class_name: "ProductField"
	  accepts_nested_attributes_for :fields, allow_destroy: true
end

app/models/search.rb
class Search < ApplicationRecord

	def products
	  @products ||= find_products
	end

	private

	def find_products
	  products = Product.order(:name)
	  products = products.where("name like ?", "%#{keywords}%") if keywords.present?
	  products = products.where(category_id: category_id) if category_id.present?
	  products = products.where("price >= ?", min_price) if min_price.present?
	  products = products.where("price <= ?", max_price) if max_price.present?
	  products
	end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
  	@cart  = current_cart
  end

  def edit
    @cart = current_cart
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
    @order = Order.new
  end
  def create
    @order = current_cart.build_order(order_params)
    @order.ip_address = request.remote_ip
    if @order.save
      if @order.purchase
        render :action => "success"
      else
        render :action => "failure"
      end
    else
      render :action => 'new'
    end
  end

  private

  def order_params
    params.require(:order).permit(:cart_id, :ip_address, :first_name, :last_name, :card_expires_on, :card_number, :card_verification)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end
    link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
  end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/letters_helper.rb
module LettersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/product_types_helper.rb
module ProductTypesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/carts/edit.html.erb
<% title "Edit page" %>

<h1>Editting Shopping Cart</h1>


<% title "Cart" %>


  <tr>
    <td class="total price" colspan="4">
      Total: <%= number_to_currency @cart.total_price %>
    </td>
  </tr>
</table>

<p>
  <% if session[:last_product_page] %>
    <%= link_to "Continue Shopping", session[:last_product_page] %> |
  <% end %>
  <%= link_to "Checkout" %>
</p>

app/views/carts/show.html.erb
<% title "Cart" %>

<h1>Shopping Cart</h1>

<table id="cart_items">
  <tr>
    <th>Product</th>
    <th>Qty</th>
    <th class="price">Unit Price</th>
    <th class="price">Full Price</th>
  </tr>
  <% for cart_item in @cart.cart_items %>
    <% if cart_item.product  %>
    <tr class="<%= cycle :odd, :even %>">
      <td><%=h cart_item.product.name %></td>
      <td class="qty"><%= cart_item.quantity %></td>
      <td class="price"><%= number_to_currency(cart_item.unit_price) %></td>
      <td class="price"><%= number_to_currency(cart_item.full_price) %></td>
    </tr>
  <% end %>
  <% end %>
  <tr>
    <td class="total price" colspan="4">
      Total: <%= number_to_currency @cart.total_price %>
    </td>
  </tr>
</table>



<p>
   <%= link_to "Continue Shopping", products_path %>
  <%= link_to "Checkout", new_order_path %>
</p>

app/views/orders/failure.html.erb
Failure

app/views/orders/new.html.erb
<%= form_for @order do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </p>
  <p>
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </p>
  <p>
    <%= f.label :card_type %><br />
    <%= f.select :card_type, [["Visa", "visa"], ["MasterCard", "master"], ["Discover", "discover"], ["American Express", "american_express"]] %>
  </p>
  <p>
    <%= f.label :card_number %><br />
    <%= f.text_field :card_number %>
  </p>
  <p>
    <%= f.label :card_verification, "Card Verification Value (CVV)" %><br />
    <%= f.text_field :card_verification %>
  </p>
  <p>
    <%= f.label :card_expires_on %><br />
    <%= f.date_select :card_expires_on, :discard_day => true, :start_year => Date.today.year, :end_year => (Date.today.year+10), :add_month_numbers => true %>
  </p>
  <p><%= f.submit "Submit" %></p>
<% end %>

app/views/orders/success.html.erb
SUCCESS!