config/routes.rb
Rails.application.routes.draw do

  scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
    root "products#index"
    resources :product_types
    resources :orders
    #resources :payment_notifications
    resources :carts
    resources :cart_items
    resources :products
    resources :searches
    resources :categories
    resources :letters
    get 'current_cart', action: :show, controller: 'carts'
    #current_cart 'cart', :controller => 'carts', :action => 'show'
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.ht
  end
  get '*path', to: redirect("/#{I18n.default_locale}/%{path}"), constraints: lambda { |req| !req.path.starts_with? "/#{I18n.default_locale}/" }
  get '', to: redirect("/#{I18n.default_locale}")
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :products
	has_ancestry
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

	def index
		##prior to addition of ancestry
		##@categories = Category.order(:name).where("name like ?", "%#{params[:term]}%")
  		##render json: @categories.map(&:name)
  		@categories = Category.all
	end

	def new
		@category = Category.new
	end

	def show
		@category = Category.find(params[:id])
	end

	def edit
		@category = Category.find(params[:id])
	end

	def update
		@category = Category.find(params[:id])
		@category.update_attributes(category_params)
		@category.save
		redirect_to @category
	end

	def create
		@category = Category.create(category_params)
		if @category.save
		redirect_to @category
		else
			render 'new'
		end
	end

	def destroy
		@category = Category.find(params[:id])
		@category.destroy
		redirect_to categories_path
	end

	private

	def category_params
		params.require(:category).permit(:name, :parent_id, :content)
	end
end

app/views/categories/_form.html.erb
<%= form_for @category do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>


  <div class="field">
    <%= f.label :parent_id %><br />
    <%= f.collection_select :parent_id, Category.order(:name), :id, :name, include_blank: true %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/_submenu.html.erb
<ul>
  <% categories.each do |category, children| %>
    <li>
      <%= link_to_unless_current category.name, category %>
      <%= render 'submenu', categories: children if children.present? %>
    </li>
  <% end %>
</ul>

app/views/categories/edit.html.erb
<h1>Edit Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing Categories</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Content</th>
    <th>Ancestry</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= category.name %></td>
    <td><%= category.content %></td>
    <td><%= category.ancestry %></td>
    <td><%= link_to 'Show', category %></td>
    <td><%= link_to 'Edit', edit_category_path(category) %></td>
    <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<% content_for :title, @category.name %>

<h1><%= @category.name %></h1>
<ul id="menu">
  <% Category.roots.each do |category| %>
    <li><%= link_to category.name, category, class: ("active" if @category.root == category) %></li>
  <% end %>
</ul>

<div id="submenu">
  <%= render 'submenu', categories: @category.root.descendants.arrange %>
</div>

<div id="breadcrumbs">
  <% @category.ancestors.each do |category| %>
    <%= link_to category.name, category %> &gt;
  <% end %>
</div>



<%= simple_format @category.content %>

app/views/categories/submenu.html.erb
<ul>
  <% categories.each do |category, children| %>
    <li>
      <%= link_to_unless_current category.name, category %>
      <%= render 'submenu', categories: children if children.present? %>
    </li>
  <% end %>
</ul>